name: Latest blog post workflow
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGPOST"
          commit_message: "Updated readme with the latest blogposts"
          feed_list: "https://esteetey.dev/rss.xml"